### ISSUE TITLE
请教一下，如何自己根据源码修改后进行 构建 docker 镜像

### ISSUE THREAD

**Issue by snycloud** [engigu/Message-Push-Nest#13]
最近在研究这个开源项目，想修改一些代码后发布到 docker， 想请教一下，如何自己根据源码修改后进行 构建 docker 镜像，并发布到自己的服务器

**Comment by engigu** [comment]
1. 修改.github/workflows/release.yml，借助github的action进行构建docker（使用的是goreleaser）
2. 修改Dockerfile，多阶段构建可以参考，https://golang.coding3min.com/%E5%B7%A5%E7%A8%8B%E5%8C%96%E5%AE%9E%E8%B7%B5/golang%E6%89%93%E9%95%9C%E5%83%8Fdockerfile%E7%9A%84%E5%86%99%E6%B3%95/
