### ISSUE TITLE
可以增加一个定时运行任务功能吗？

### ISSUE THREAD

**Issue by hausen1012** [engigu/Message-Push-Nest#15]
目前发送消息功能已经实现了，希望可以通过表单进行增加 标题 、内容 、任务、还有时间。这个时间可以是定时的，也可以选择循环执行，如果支持 cron 表达式最好。

比如我想每天早上 9 点和下午 6 点定时提醒自己打卡，我就只需要在页面配置就行了，而不需要再去linux添加定时任务，调用本程序的接口。

还有一个疑问是，任务只支持 post 调用吗？是否支持 get 请求

**Comment by engigu** [comment]
1. 定时消息可以实现。但是消息内容一直是固定的吗？
2. 考虑到get请求发消息的现在比较少见，所以暂时没有支持。

**Comment by hausen1012** [comment]
1. 可以选择添加一次性任务或者循环任务。

一般循环任务的消息标题和内容都是固定的，也就是说到达定时任务执行的时刻，那么只需要调用任务，并将创建时填入的标题和内容添加上即可。

我觉得这是一个非常不错的功能，它可以替代我在日历上标记重要日子并闹钟提醒我。

2. 只是觉得get请求在某些情况下会比较方便一点，当然我也是看见[别的项目](https://github.com/LeslieLeung/heimdallr)这样，并且可以支持设置 token，这样防止被扫描到？虽然我也不知道几率是多大。

**Comment by engigu** [comment]
后续会考虑支持这两个功能

**Comment by hausen1012** [comment]
感谢大佬，期待这个功能。祝您生活愉快！

**Comment by hausen1012** [comment]
不知道我说的这个任务和程序现有这个任务是否冲突，现有这个应该只是一个等待调用的接口？关于如何设计或者命名可能还需要斟酌一下

**Comment by engigu** [comment]
不冲突

**Comment by hausen1012** [comment]
好的好的

**Comment by engigu** [comment]
已经更新定时消息

https://github.com/engigu/Message-Push-Nest/releases/tag/v0.1.6

**Comment by hausen1012** [comment]
![image](https://github.com/engigu/Message-Push-Nest/assets/50026605/c4313dda-9093-46ba-a5ab-922203d7d4d0)
