### ISSUE TITLE
希望支持 sqlite

### ISSUE THREAD

**Issue by hausen1012** [engigu/Message-Push-Nest#17]
项目可以支持 sqlite吗？对于轻量级的项目似乎挺不错的，不要依赖 mysql，很吃内存

同时希望可以精简一下docker部署方式，比如容器启动时自动在 conf 目录下生成配置文件，程序自行判断数据库是否需要初始化而不是在配置文件中填写。

**Comment by engigu** [comment]
不支持的原因是：gorm v1的orm相比于其他语言的orm，不同数据库的支持不够通用，通过model的自动mirgrate不能完美支持，不能自动适配不同的model语法。拿我擅长的python，适配非常简单，但是我看了gorm v1的很多资料，同时支持实现不是很完美。
后续会观察下，看下有没更好的方案。

**Comment by hausen1012** [comment]
嗯嗯，辛苦大佬，这个优先级其实不高。如果能先把任务计划做出了就好了

**Comment by engigu** [comment]
现在已经支持sqlite
https://github.com/engigu/Message-Push-Nest/releases/tag/v0.2.0
