### ISSUE TITLE
clone项目运行后，出现test.go 404

### ISSUE THREAD

**Issue by bayhax** [engigu/Message-Push-Nest#7]
没用过go语言，但是想本地运行项目。 clone下来，运行后，出现以下错误
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/8f010ce4-cf3a-4627-878a-2ad266a730a4)
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/48c3db2c-47b7-430c-9b4b-c12bf9232523)
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/5565e2d1-7cc6-48bf-b41f-da7ec34e527a)

**Comment by engigu** [comment]
是因为没有初始化数据库
https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-

1. 下载最新的系统版本对应的release， 解压
2. 新建一个数据库
3. 重命名conf/app.example.ini为conf/app.ini
4. 修改app.ini对应的配置
5. 启动项目会自动创建表和账号
第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
后续不需要开启这个配置

完整配置参考如下：
``` ini
[app]
JwtSecret = message-nest
RuntimeRootPath = runtime/
LogLevel = INFO

; init table data, first run set enable
; 首次运行打开这个，会自动初始化表和数据
InitData = enable

[server]
; debug or release
RunMode = release
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60
; use embed html static file
; 是否使用embed打包的惊天资源
; EmbedHtml = disable   

[database]
Type = mysql
User = root
Password = password
Host = 123.1.1.1
Name = db_name
Port = 3306
; 表前缀
TablePrefix = message_
; 是否打开sql打印
; SqlDebug = enable
```

**Comment by engigu** [comment]
> 没用过go语言，但是想本地运行项目。 clone下来，运行后，出现以下错误 ![image](https://private-user-images.githubusercontent.com/23427243/299870440-8f010ce4-cf3a-4627-878a-2ad266a730a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDA0ODAsIm5iZiI6MTcwNjI0MDE4MCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzA0NDAtOGYwMTBjZTQtY2YzYS00NjI3LTg3OGEtMmFkMjY2YTczMGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzMzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MGZlZmI1NmE2MWYzM2EyYjI2MThmYmYwODE5N2I5ZDE3YmRiMzc5ZWE5NmY0MjQyNDQ0OTc5NjYyOTJjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._D5nxBFb-BiE3S8ZT7GSIFquPaxkFAUI2i2bacbWLOg) ![image](https://private-user-images.githubusercontent.com/23427243/299870468-48c3db2c-47b7-430c-9b4b-c12bf9232523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDA0ODAsIm5iZiI6MTcwNjI0MDE4MCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzA0NjgtNDhjM2RiMmMtNDdiNy00MzBjLTliNGItYzEyYmY5MjMyNTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzMzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZjhiZTVhZWU2NmUyNzY3NDI5NTBkOTI4NTU5NGZiNmQ2MzMyNWFlOTAyZmE1M2VmNmVkZjMyMzliYzJmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FG5gFKmY2_F6_LDCPcd9CKqCDXwiGYyXF_loGcMo2Jo) ![image](https://private-user-images.githubusercontent.com/23427243/299870670-5565e2d1-7cc6-48bf-b41f-da7ec34e527a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDA0ODAsIm5iZiI6MTcwNjI0MDE4MCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzA2NzAtNTU2NWUyZDEtN2NjNi00OGJmLWI0MWYtZGE3ZWMzNGU1MjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzMzYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNmI3YjE2ZDE5ZDg3YmNiNDU0M2IyY2ViY2QyZTA3MWQwN2M4YmJkZTY2MjNmYWI3OTc3NTc2NGIzZTQ4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KhvoaoIoiWV0BEHjM5Ko0rkFs3fIa-SP1CXO-C52k7A)


是因为没有初始化数据库
https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-

1. 下载最新的系统版本对应的release， 解压
2. 新建一个数据库
3. 重命名conf/app.example.ini为conf/app.ini
4. 修改app.ini对应的配置
5. 启动项目会自动创建表和账号
第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
后续不需要开启这个配置

完整配置参考如下：
``` ini
[app]
JwtSecret = message-nest
RuntimeRootPath = runtime/
LogLevel = INFO

; init table data, first run set enable
; 首次运行打开这个，会自动初始化表和数据
InitData = enable

[server]
; debug or release
RunMode = release
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60
; use embed html static file
; 是否使用embed打包的惊天资源
; EmbedHtml = disable   

[database]
Type = mysql
User = root
Password = password
Host = 123.1.1.1
Name = db_name
Port = 3306
; 表前缀
TablePrefix = message_
; 是否打开sql打印
; SqlDebug = enable
```

**Comment by bayhax** [comment]
> 是因为没有初始化数据库 https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-
> 
> 1. 下载最新的系统版本对应的release， 解压
> 2. 新建一个数据库
> 3. 重命名conf/app.example.ini为conf/app.ini
> 4. 修改app.ini对应的配置
> 5. 启动项目会自动创建表和账号
>    第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
>    后续不需要开启这个配置
> 
> 完整配置参考如下：
> 
> ```ini
> [app]
> JwtSecret = message-nest
> RuntimeRootPath = runtime/
> LogLevel = INFO
> 
> ; init table data, first run set enable
> ; 首次运行打开这个，会自动初始化表和数据
> InitData = enable
> 
> [server]
> ; debug or release
> RunMode = release
> HttpPort = 8000
> ReadTimeout = 60
> WriteTimeout = 60
> ; use embed html static file
> ; 是否使用embed打包的静态资源
> ; EmbedHtml = disable   
> 
> [database]
> Type = mysql
> User = root
> Password = password
> Host = 123.1.1.1
> Name = db_name
> Port = 3306
> ; 表前缀
> TablePrefix = message_
> ; 是否打开sql打印
> ; SqlDebug = enable
> ```

还是不行，应该是没有初始化成功
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/f8d07273-61b5-494d-bc44-8723121ee05d)

**Comment by engigu** [comment]
> > 是因为没有初始化数据库 https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-
> > 
> > 1. 下载最新的系统版本对应的release， 解压
> > 2. 新建一个数据库
> > 3. 重命名conf/app.example.ini为conf/app.ini
> > 4. 修改app.ini对应的配置
> > 5. 启动项目会自动创建表和账号
> >    第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
> >    后续不需要开启这个配置
> > 
> > 完整配置参考如下：
> > ```ini
> > [app]
> > JwtSecret = message-nest
> > RuntimeRootPath = runtime/
> > LogLevel = INFO
> > 
> > ; init table data, first run set enable
> > ; 首次运行打开这个，会自动初始化表和数据
> > InitData = enable
> > 
> > [server]
> > ; debug or release
> > RunMode = release
> > HttpPort = 8000
> > ReadTimeout = 60
> > WriteTimeout = 60
> > ; use embed html static file
> > ; 是否使用embed打包的静态资源
> > ; EmbedHtml = disable   
> > 
> > [database]
> > Type = mysql
> > User = root
> > Password = password
> > Host = 123.1.1.1
> > Name = db_name
> > Port = 3306
> > ; 表前缀
> > TablePrefix = message_
> > ; 是否打开sql打印
> > ; SqlDebug = enable
> > ```
> 
> 还是不行，应该是没有初始化成功 ![image](https://private-user-images.githubusercontent.com/23427243/299873903-1734ab2c-37de-49da-9dc3-7ce5254c0b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDExMDMsIm5iZiI6MTcwNjI0MDgwMywicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzM5MDMtMTczNGFiMmMtMzdkZS00OWRhLTlkYzMtN2NlNTI1NGMwYjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzZkODEzZmI3ZDM4YzEyZWNlNDM5YTIzZDhlNWZhN2I3ZDhmNGM2NTQ4MjllMjAwZWQ1MWFiMjU1Njc3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUk5XUEQ6HkJdhNmK5zCASSH27cIqP1uVhiamI__oAM)

非常感谢进一步提问，可以将你的app.ini隐去数据库必要信息提供一份吗

**Comment by bayhax** [comment]
> > > 是因为没有初始化数据库 https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-
> > > 
> > > 1. 下载最新的系统版本对应的release， 解压
> > > 2. 新建一个数据库
> > > 3. 重命名conf/app.example.ini为conf/app.ini
> > > 4. 修改app.ini对应的配置
> > > 5. 启动项目会自动创建表和账号
> > >    第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
> > >    后续不需要开启这个配置
> > > 
> > > 完整配置参考如下：
> > > ```ini
> > > [app]
> > > JwtSecret = message-nest
> > > RuntimeRootPath = runtime/
> > > LogLevel = INFO
> > > 
> > > ; init table data, first run set enable
> > > ; 首次运行打开这个，会自动初始化表和数据
> > > InitData = enable
> > > 
> > > [server]
> > > ; debug or release
> > > RunMode = release
> > > HttpPort = 8000
> > > ReadTimeout = 60
> > > WriteTimeout = 60
> > > ; use embed html static file
> > > ; 是否使用embed打包的静态资源
> > > ; EmbedHtml = disable   
> > > 
> > > [database]
> > > Type = mysql
> > > User = root
> > > Password = password
> > > Host = 123.1.1.1
> > > Name = db_name
> > > Port = 3306
> > > ; 表前缀
> > > TablePrefix = message_
> > > ; 是否打开sql打印
> > > ; SqlDebug = enable
> > > ```
> > 
> > 
> > 还是不行，应该是没有初始化成功 ![image](https://private-user-images.githubusercontent.com/23427243/299873903-1734ab2c-37de-49da-9dc3-7ce5254c0b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDExMDMsIm5iZiI6MTcwNjI0MDgwMywicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzM5MDMtMTczNGFiMmMtMzdkZS00OWRhLTlkYzMtN2NlNTI1NGMwYjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzZkODEzZmI3ZDM4YzEyZWNlNDM5YTIzZDhlNWZhN2I3ZDhmNGM2NTQ4MjllMjAwZWQ1MWFiMjU1Njc3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUk5XUEQ6HkJdhNmK5zCASSH27cIqP1uVhiamI__oAM)
> 
> 非常感谢进一步提问，可以将你的app.ini隐去数据库必要信息提供一份吗

配置是这样的
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/7646ae38-e402-460a-b414-4e7d8a6b5c87)

**Comment by engigu** [comment]
> > > > 是因为没有初始化数据库 https://github.com/engigu/Message-Push-Nest?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-
> > > > 
> > > > 1. 下载最新的系统版本对应的release， 解压
> > > > 2. 新建一个数据库
> > > > 3. 重命名conf/app.example.ini为conf/app.ini
> > > > 4. 修改app.ini对应的配置
> > > > 5. 启动项目会自动创建表和账号
> > > >    第一次运行将app.ini中的app.InitData设置为enable，会自动进行表数据的初始化
> > > >    后续不需要开启这个配置
> > > > 
> > > > 完整配置参考如下：
> > > > ```ini
> > > > [app]
> > > > JwtSecret = message-nest
> > > > RuntimeRootPath = runtime/
> > > > LogLevel = INFO
> > > > 
> > > > ; init table data, first run set enable
> > > > ; 首次运行打开这个，会自动初始化表和数据
> > > > InitData = enable
> > > > 
> > > > [server]
> > > > ; debug or release
> > > > RunMode = release
> > > > HttpPort = 8000
> > > > ReadTimeout = 60
> > > > WriteTimeout = 60
> > > > ; use embed html static file
> > > > ; 是否使用embed打包的静态资源
> > > > ; EmbedHtml = disable   
> > > > 
> > > > [database]
> > > > Type = mysql
> > > > User = root
> > > > Password = password
> > > > Host = 123.1.1.1
> > > > Name = db_name
> > > > Port = 3306
> > > > ; 表前缀
> > > > TablePrefix = message_
> > > > ; 是否打开sql打印
> > > > ; SqlDebug = enable
> > > > ```
> > > 
> > > 
> > > 还是不行，应该是没有初始化成功 ![image](https://private-user-images.githubusercontent.com/23427243/299873903-1734ab2c-37de-49da-9dc3-7ce5254c0b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDExMDMsIm5iZiI6MTcwNjI0MDgwMywicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzM5MDMtMTczNGFiMmMtMzdkZS00OWRhLTlkYzMtN2NlNTI1NGMwYjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzNDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzZkODEzZmI3ZDM4YzEyZWNlNDM5YTIzZDhlNWZhN2I3ZDhmNGM2NTQ4MjllMjAwZWQ1MWFiMjU1Njc3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUk5XUEQ6HkJdhNmK5zCASSH27cIqP1uVhiamI__oAM)
> > 
> > 
> > 非常感谢进一步提问，可以将你的app.ini隐去数据库必要信息提供一份吗
> 
> 配置是这样的 ![image](https://private-user-images.githubusercontent.com/23427243/299875047-7646ae38-e402-460a-b414-4e7d8a6b5c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDE1NzgsIm5iZiI6MTcwNjI0MTI3OCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4NzUwNDctNzY0NmFlMzgtZTQwMi00NjBhLWI0MTQtNGU3ZDhhNmI1Yzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAzNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOGRhZGQ1ZDRjOGRjM2YwOTcyNzFhNDRjNzhhZjMzNzA0OGQxNWVmMzFkNjAzNTQxMjdhYjBiYjdhM2RhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2O2recKrAQkU41rKWag8KIYIl_13zG0U-d4Q5-6wzzg)

请问数据库版本是多少

**Comment by bayhax** [comment]
> ~请问数据库版本是多少~
> 
> 已经确认为mysql8.0语法适配有点问题，已经更新，请下载最新版本，感谢反馈

感谢！这个问题是解决了。
但是本地运行的时候，会出现找不到web/dist目录的情况，是需要build吗？
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/57cffe46-5460-4722-b37d-04f4bdaea67b)

**Comment by engigu** [comment]
如果是

> > ~请问数据库版本是多少~
> > 已经确认为mysql8.0语法适配有点问题，已经更新，请下载最新版本，感谢反馈
> 
> 感谢！这个问题是解决了。 但是本地运行的时候，会出现找不到web/dist目录的情况，是需要build吗？ ![image](https://private-user-images.githubusercontent.com/23427243/299890661-57cffe46-5460-4722-b37d-04f4bdaea67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDk2OTgsIm5iZiI6MTcwNjI0OTM5OCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4OTA2NjEtNTdjZmZlNDYtNTQ2MC00NzIyLWIzN2QtMDRmNGJkYWVhNjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZThjMjE1NzJkMTI3MWE5MjIyMTdiOTdmOTZkYWFiN2ZiMTcxMTQ0YTc1MjMxMTE0ZjYyNjFhZmFlYWQzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NChHlIcCexxXDXRtyaWIqH-BtHqSb3ZMx3bqU7jYSuk)
  


感谢反馈，请拉取最新代码

**Comment by bayhax** [comment]
> > > ~请问数据库版本是多少~
> > > 已经确认为mysql8.0语法适配有点问题，已经更新，请下载最新版本，感谢反馈
> > 
> > 
> > 感谢！这个问题是解决了。 但是本地运行的时候，会出现找不到web/dist目录的情况，是需要build吗？ ![image](https://private-user-images.githubusercontent.com/23427243/299890661-57cffe46-5460-4722-b37d-04f4bdaea67b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDk2OTgsIm5iZiI6MTcwNjI0OTM5OCwicGF0aCI6Ii8yMzQyNzI0My8yOTk4OTA2NjEtNTdjZmZlNDYtNTQ2MC00NzIyLWIzN2QtMDRmNGJkYWVhNjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZThjMjE1NzJkMTI3MWE5MjIyMTdiOTdmOTZkYWFiN2ZiMTcxMTQ0YTc1MjMxMTE0ZjYyNjFhZmFlYWQzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NChHlIcCexxXDXRtyaWIqH-BtHqSb3ZMx3bqU7jYSuk)
> 
> 感谢反馈，请拉取最新代码

拉取最新代码了，又出现路径找不到的问题了。
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/c8562e8a-1b72-4a84-b33d-2eb95e403956)
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/0b804289-84c8-4bea-97e2-dda81f75023a)

**Comment by engigu** [comment]
抱歉。我的说明没有写清楚😭，待会我会更加完善一下。

  与这个配置有关`EmbedHtml = disable`，这个配置可以理解为单应用模式（或者前后端分离）的开关
1. 取消这个配置的注释，表示前后端分离，表示go服务启动的时候只会有api服务，需要到web目录下，npm run dev启动前端项目。然后访问前端项目提示的端口服务，一般是127.0.0.1:5173。
2. 注释这个配置，表示单应用，启动go服务，会把web/dist目录下文件作为前端静态资源。

在理解上面的处理之后，解决方式有两种：
1. 取消这个配置的注释，cd web && npm i && npm run dev ,  然后访问 127.0.0.1:5173
2. 继续注释这个配置，cd web && npm i && npm run build ,  然后访问 127.0.0.1:8000

**Comment by bayhax** [comment]
> 抱歉。我的说明没有写清楚😭，待会我会更加完善一下。
> 
> 与这个配置有关`EmbedHtml = disable`，这个配置可以理解为单应用模式（或者前后端分离）的开关
> 
> 1. 取消这个配置的注释，表示前后端分离，表示go服务启动的时候只会有api服务，需要到web目录下，npm run dev启动前端项目。然后访问前端项目提示的端口服务，一般是127.0.0.1:5173。
> 2. 注释这个配置，表示单应用，启动go服务，会把web/dist目录下文件作为前端静态资源。
> 
> 在理解上面的处理之后，解决方式有两种：
> 
> 1. 取消这个配置的注释，cd web && npm i && npm run dev ,  然后访问 127.0.0.1:5173
> 2. 继续注释这个配置，cd web && npm i && npm run build ,  然后访问 127.0.0.1:8000

感谢感谢，不过，您可能还需要解决一下，本地访问时，跨域的问题，不然没办法登录
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/1e491b40-b643-45b6-82e1-24fbd9d740a8)

**Comment by engigu** [comment]
``` ini
[server]
; debug or release
RunMode = debug  
```
设置为debug

**Comment by bayhax** [comment]
设置为 RunMode = debug 后也还是不行，还是出现上面的错误

**Comment by engigu** [comment]
routers/router.go:16

``` go
// AppendCors 添加是否跨域（debug模式开启）
func AppendCors(app *gin.Engine) {
	if setting.ServerSetting.RunMode == "debug" {
		app.Use(middleware.Cors())
	}
}
```
如果是debug模式，会自动添加跨域
检查下这个debug值有没有前后空格，go服务是否重启😭

**Comment by bayhax** [comment]
> routers/router.go:16
> 
> ```go
> // AppendCors 添加是否跨域（debug模式开启）
> func AppendCors(app *gin.Engine) {
> 	if setting.ServerSetting.RunMode == "debug" {
> 		app.Use(middleware.Cors())
> 	}
> }
> ```
> 
> 如果是debug模式，会自动添加跨域 检查下这个debug值有没有前后空格，go服务是否重启😭

可能是中间件有问题？我加了两行打印输出，是在debug模式下运行的
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/43ff8de5-e59e-4fb8-9afa-8f94f8abfc97)
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/2220fa37-a75b-423b-b224-73ebbd7af7a2)

**Comment by engigu** [comment]
关闭谷歌浏览器的配置
url访问 `chrome://flags/#block-insecure-private-network-requests`, 然后disable

https://stackoverflow.com/questions/66534759/cors-error-on-request-to-localhost-dev-server-from-remote-site

**Comment by bayhax** [comment]
> https://stackoverflow.com/questions/66534759/cors-error-on-request-to-localhost-dev-server-from-remote-site

您好，您提供的stackoverflow上的不是解决这个问题的。
应该是配置debug模式下访问的是http://0.0.0.0。但是前端走的却是http://localhost，出现了跨域问题。我给配置成localhost就正常了，您可以检查检查。
![image](https://github.com/engigu/Message-Push-Nest/assets/23427243/8b37fda5-7e62-4d60-955c-406d5075a7dc)

**Comment by engigu** [comment]
好的，感谢反馈，后续会改动这个启动的url提示信息。
请拉取下最新的代码，有mysql8语法适配改动

**Comment by bayhax** [comment]
> 好的，感谢反馈，后续会改动这个启动的url提示信息。 请拉取下最新的代码，有mysql8语法适配改动

好的，感谢感谢。

**Comment by engigu** [comment]
> > 好的，感谢反馈，后续会改动这个启动的url提示信息。 请拉取下最新的代码，有mysql8语法适配改动
> 
> 好的，感谢感谢。 有一点小小的建议，可以在README中增加下如何 新增任务的详细操作步骤描述，这样使用起来会清晰一些。

好的，谢谢你的建议
